/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.tetras;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class PizzaTest {
    @Test
    void testCreatePizza() {
        // Reine : champignons, emmental, sauce tomate, jambon
        PizzaBuilder monPizzaiolo = new PizzaBuilder();
        monPizzaiolo.addChampignons();
        monPizzaiolo.addEmmental();
        monPizzaiolo.addJambon();
        monPizzaiolo.addSauceTomate();

        Pizza maPizza = monPizzaiolo.build();
        // Test
        assertFalse(maPizza.isAnchois());
        assertTrue(maPizza.isChampignons());
        assertFalse(maPizza.isCremeFraiche());
        assertTrue(maPizza.isEmmental());
        assertTrue(maPizza.isJambon());
        assertFalse(maPizza.isLardons());
        assertTrue(maPizza.isSauceTomate());
    }
}
