/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.tetras;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class SupermanTest {
    @Test
    void testSingleton() {

        Superman monSuperman1 = new Superman();
        Superman monSuperman2 = new Superman();
        assertEquals(monSuperman1, monSuperman2);
    }
}
